owner: SRESchool
repo: AllHolidaylandmark-monitor-upptime
sites:
  - name: Bangalore Orbit
    url: https://bangaloreorbit.com
    check_ssl: true
  - name: Bhopal Orbit
    url: https://bhopalorbit.com
    check_ssl: true
  - name: Gujarat  Gujarat Orbit
    url: https://gujaratorbit.com
    check_ssl: true
  - name: Chennai Orbit
    url: https://chennaiorbit.com
    check_ssl: true
  - name: Holiday Landmark
    url: https://holidaylandmark.com
    check_ssl: true
  - name: Kerala Orbit
    url: https://keralaorbit.in
    check_ssl: true
  - name: Mera Apna Bihar
    url: https://meraapnabihar.com
    check_ssl: true
  - name: Mumbai Orbit
    url: https://mumbaiorbit.in
    check_ssl: true
    port: 80
    check: "tcp-ping"
    ipv6: true
status-website:
  cname: # Add custom domain if you have one, else leave blank
  baseUrl: /AllHolidaylandmark-monitor-upptime
  logoUrl: https://raw.githubusercontent.com/upptime/upptime/master/assets/logo.png
  name: Holiday Landmark Uptime Monitor
  introTitle: "**Holiday Landmark** Website Uptime Monitor"
  introMessage: Real-time monitoring for Holiday Landmark websites.
  favicon: https://raw.githubusercontent.com/upptime/upptime/master/assets/favicon.png
  theme: light
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/SRESchool/AllHolidaylandmark-monitor-upptime
workflowSchedule:
  graphs: "*/5 * * * *"
  responseTime: "*/5 * * * *"
  staticSite: "*/5 * * * *"
  summary: "*/5 * * * *"
  updateTemplate: "*/5 * * * *"
  updates: "*/5 * * * *"
  uptime: "*/5 * * * *"
